export const LEVELS = {
  easy: {
    label: 'Easy', badgeClass: 'badge-easy', hints: 5, points: 10,
    words: [
      { word: 'APPLE',  category: 'Fruit',       hint: 'Keeps the doctor away' },
      { word: 'CLOUD',  category: 'Nature',       hint: 'Found in the sky' },
      { word: 'DANCE',  category: 'Activity',     hint: 'Move to music' },
      { word: 'EAGLE',  category: 'Bird',         hint: 'National bird of the USA' },
      { word: 'FLAME',  category: 'Element',      hint: 'Hot and flickering' },
      { word: 'GRAPE',  category: 'Fruit',        hint: 'Used to make wine' },
      { word: 'HORSE',  category: 'Animal',       hint: 'Gallops and neighs' },
      { word: 'PLANT',  category: 'Nature',       hint: 'Grows in soil' },
      { word: 'RIVER',  category: 'Nature',       hint: 'Flows to the sea' },
      { word: 'SMILE',  category: 'Expression',   hint: 'Shows happiness' },
      { word: 'TIGER',  category: 'Animal',       hint: 'Striped big cat' },
      { word: 'PIZZA',  category: 'Food',         hint: 'Italian with toppings' },
      { word: 'BEACH',  category: 'Place',        hint: 'Sand meets ocean' },
      { word: 'CROWN',  category: 'Object',       hint: 'Worn by royalty' },
      { word: 'FROST',  category: 'Nature',       hint: 'Cold winter coating' },
    ],
  },
  medium: {
    label: 'Medium', badgeClass: 'badge-medium', hints: 4, points: 20,
    words: [
      { word: 'FATHOM',  category: 'Measurement', hint: 'Unit of water depth' },
      { word: 'GOBLIN',  category: 'Fantasy',     hint: 'Mischievous creature' },
      { word: 'JIGSAW',  category: 'Puzzle',      hint: 'Pieces fit together' },
      { word: 'LOCKET',  category: 'Jewelry',     hint: 'Holds a tiny photo' },
      { word: 'MUFFIN',  category: 'Baked good',  hint: 'Eaten at breakfast' },
      { word: 'NOODLE',  category: 'Food',        hint: 'Long pasta strand' },
      { word: 'OYSTER',  category: 'Seafood',     hint: 'May contain a pearl' },
      { word: 'PARCEL',  category: 'Object',      hint: 'Wrapped package' },
      { word: 'QUARTZ',  category: 'Mineral',     hint: 'Common crystal' },
      { word: 'RIDDLE',  category: 'Puzzle',      hint: 'A clever question' },
      { word: 'STRIPE',  category: 'Pattern',     hint: 'Zebra has these' },
      { word: 'TUNDRA',  category: 'Biome',       hint: 'Frozen Arctic plain' },
      { word: 'VELVET',  category: 'Fabric',      hint: 'Soft and luxurious' },
      { word: 'WALRUS',  category: 'Animal',      hint: 'Has long tusks' },
      { word: 'ZIPPER',  category: 'Object',      hint: 'Fastens clothing' },
    ],
  },
  hard: {
    label: 'Hard', badgeClass: 'badge-hard', hints: 3, points: 30,
    words: [
      { word: 'ALCHEMY',      category: 'History',    hint: 'Medieval proto-science' },
      { word: 'BLIZZARD',     category: 'Weather',    hint: 'Severe snowstorm' },
      { word: 'CARRIAGE',     category: 'Transport',  hint: 'Horse-drawn vehicle' },
      { word: 'DRIFTWOOD',    category: 'Nature',     hint: 'Wood washed ashore' },
      { word: 'ELEPHANT',     category: 'Animal',     hint: 'Largest land animal' },
      { word: 'FORTRESS',     category: 'Structure',  hint: 'Heavily defended castle' },
      { word: 'GRAPEVINE',    category: 'Plant',      hint: 'Rumours travel on it' },
      { word: 'HOURGLASS',    category: 'Object',     hint: 'Measures time with sand' },
      { word: 'ICICLE',       category: 'Nature',     hint: 'Hanging frozen water' },
      { word: 'JELLYFISH',    category: 'Animal',     hint: 'Boneless ocean drifter' },
      { word: 'LABYRINTH',    category: 'Structure',  hint: 'Complex maze' },
      { word: 'MOONLIGHT',    category: 'Nature',     hint: "Night's soft glow" },
      { word: 'NIGHTMARE',    category: 'Dream',      hint: 'A frightening sleep vision' },
      { word: 'OBSIDIAN',     category: 'Mineral',    hint: 'Volcanic black glass' },
      { word: 'KALEIDOSCOPE', category: 'Toy',        hint: 'Colorful rotating patterns' },
    ],
  },
};

export const LEVEL_ORDER = ['easy', 'medium', 'hard'];
