export const LEVELS = {
  easy: {
    label: 'Easy', badgeClass: 'badge-easy', hints: 5, points: 10,
    words: [
      { word: 'APPLE',  category: 'Fruit',       hint: 'Keeps the doctor away' },
      { word: 'CLOUD',  category: 'Nature',       hint: 'Found in the sky' },
      { word: 'DANCE',  category: 'Activity',     hint: 'Move to music' },
      { word: 'EAGLE',  category: 'Bird',         hint: 'National bird of the USA' },
      { word: 'FLAME',  category: 'Element',      hint: 'Hot and flickering' },
      { word: 'GRAPE',  category: 'Fruit',        hint: 'Used to make wine' },
      { word: 'HORSE',  category: 'Animal',       hint: 'Gallops and neighs' },
      { word: 'PLANT',  category: 'Nature',       hint: 'Grows in soil' },
      { word: 'RIVER',  category: 'Nature',       hint: 'Flows to the sea' },
      { word: 'SMILE',  category: 'Expression',   hint: 'Shows happiness' },
      { word: 'TIGER',  category: 'Animal',       hint: 'Striped big cat' },
      { word: 'PIZZA',  category: 'Food',         hint: 'Italian with toppings' },
      { word: 'BEACH',  category: 'Place',        hint: 'Sand meets ocean' },
      { word: 'CROWN',  category: 'Object',       hint: 'Worn by royalty' },
      { word: 'FROST',  category: 'Nature',       hint: 'Cold winter coating' },
      { word: 'BREAD',  category: 'Food',         hint: 'Baked from dough' },
      { word: 'CHAIR',  category: 'Furniture',    hint: 'You sit on it' },
      { word: 'LIGHT',  category: 'Element',      hint: 'Opposite of dark' },
      { word: 'OCEAN',  category: 'Nature',       hint: 'Vast body of salt water' },
      { word: 'STORM',  category: 'Weather',      hint: 'Thunder and lightning' },
      { word: 'BRUSH',  category: 'Tool',         hint: 'Used for painting or hair' },
      { word: 'CANDY',  category: 'Food',         hint: 'Sweet treat' },
      { word: 'DRAFT',  category: 'Object',       hint: 'A breeze through a gap' },
      { word: 'FLUTE',  category: 'Music',        hint: 'Wind instrument you blow across' },
      { word: 'GLOBE',  category: 'Object',       hint: 'Spherical map of Earth' },
      { word: 'HONEY',  category: 'Food',         hint: 'Made by bees' },
      { word: 'IVORY',  category: 'Color',        hint: 'Off-white like tusks' },
      { word: 'JUDGE',  category: 'Profession',   hint: 'Presides over a courtroom' },
      { word: 'KNIFE',  category: 'Tool',         hint: 'Has a sharp blade' },
      { word: 'LEMON',  category: 'Fruit',        hint: 'Sour yellow citrus' },
      { word: 'MOUSE',  category: 'Animal',       hint: 'Small and squeaky' },
      { word: 'NURSE',  category: 'Profession',   hint: 'Cares for patients' },
      { word: 'OLIVE',  category: 'Food',         hint: 'Used in Mediterranean cooking' },
      { word: 'PENNY',  category: 'Currency',     hint: 'Smallest US coin' },
      { word: 'QUILT',  category: 'Object',       hint: 'Patchwork bed cover' },
      { word: 'ROBIN',  category: 'Bird',         hint: 'Red-breasted songbird' },
      { word: 'SHEEP',  category: 'Animal',       hint: 'Gives us wool' },
      { word: 'TRAIN',  category: 'Transport',    hint: 'Runs on tracks' },
      { word: 'UNCLE',  category: 'Family',       hint: 'Your parent\'s brother' },
      { word: 'VIOLA',  category: 'Music',        hint: 'Larger cousin of the violin' },
    ],
  },
  medium: {
    label: 'Medium', badgeClass: 'badge-medium', hints: 4, points: 20,
    words: [
      { word: 'FATHOM',  category: 'Measurement', hint: 'Unit of water depth' },
      { word: 'GOBLIN',  category: 'Fantasy',     hint: 'Mischievous creature' },
      { word: 'JIGSAW',  category: 'Puzzle',      hint: 'Pieces fit together' },
      { word: 'LOCKET',  category: 'Jewelry',     hint: 'Holds a tiny photo' },
      { word: 'MUFFIN',  category: 'Baked good',  hint: 'Eaten at breakfast' },
      { word: 'NOODLE',  category: 'Food',        hint: 'Long pasta strand' },
      { word: 'OYSTER',  category: 'Seafood',     hint: 'May contain a pearl' },
      { word: 'PARCEL',  category: 'Object',      hint: 'Wrapped package' },
      { word: 'QUARTZ',  category: 'Mineral',     hint: 'Common crystal' },
      { word: 'RIDDLE',  category: 'Puzzle',      hint: 'A clever question' },
      { word: 'STRIPE',  category: 'Pattern',     hint: 'Zebra has these' },
      { word: 'TUNDRA',  category: 'Biome',       hint: 'Frozen Arctic plain' },
      { word: 'VELVET',  category: 'Fabric',      hint: 'Soft and luxurious' },
      { word: 'WALRUS',  category: 'Animal',      hint: 'Has long tusks' },
      { word: 'ZIPPER',  category: 'Object',      hint: 'Fastens clothing' },
      { word: 'ANCHOR',  category: 'Nautical',    hint: 'Holds a ship in place' },
      { word: 'BADGER',  category: 'Animal',      hint: 'Black-and-white burrowing mammal' },
      { word: 'CACTUS',  category: 'Plant',       hint: 'Thrives in the desert' },
      { word: 'DAGGER',  category: 'Weapon',      hint: 'Short double-edged blade' },
      { word: 'FENDER',  category: 'Object',      hint: 'Protects a car wheel arch' },
      { word: 'GEYSER',  category: 'Nature',      hint: 'Erupts boiling water' },
      { word: 'HAMLET',  category: 'Place',       hint: 'Tiny village; also a Shakespeare play' },
      { word: 'INDIGO',  category: 'Color',       hint: 'Deep blue-purple hue' },
      { word: 'JUNGLE',  category: 'Biome',       hint: 'Dense tropical forest' },
      { word: 'KITTEN',  category: 'Animal',      hint: 'Baby cat' },
      { word: 'LANCER',  category: 'History',     hint: 'Cavalry soldier with a spear' },
      { word: 'MARBLE',  category: 'Material',    hint: 'Smooth stone used in sculpture' },
      { word: 'NUTMEG',  category: 'Spice',       hint: 'Warm spice grated on eggnog' },
      { word: 'ORCHID',  category: 'Plant',       hint: 'Exotic tropical flower' },
      { word: 'PUFFIN',  category: 'Bird',        hint: 'Seabird with a colorful beak' },
      { word: 'QUINOA', category: 'Food',         hint: 'South American grain superfood' },
      { word: 'ROTUNDA', category: 'Structure',   hint: 'Round room with a dome' },
      { word: 'SALMON',  category: 'Seafood',     hint: 'Pink fish that swims upstream' },
      { word: 'TURBAN',  category: 'Clothing',    hint: 'Head wrap worn in many cultures' },
      { word: 'URCHIN',  category: 'Animal',      hint: 'Spiny creature of the sea floor' },
      { word: 'VORTEX',  category: 'Nature',      hint: 'Spinning whirlpool of air or water' },
      { word: 'WEASEL',  category: 'Animal',      hint: 'Slender, sneaky mammal' },
      { word: 'FALLOW',  category: 'Farming',     hint: 'Unplanted field left to rest' },
      { word: 'GROTTO',  category: 'Place',       hint: 'Small scenic cave' },
      { word: 'HARLOT',  category: 'History',     hint: 'Archaic term for a wayward woman' },
    ],
  },
  hard: {
    label: 'Hard', badgeClass: 'badge-hard', hints: 3, points: 30,
    words: [
      { word: 'ALCHEMY',       category: 'History',    hint: 'Medieval proto-science' },
      { word: 'BLIZZARD',      category: 'Weather',    hint: 'Severe snowstorm' },
      { word: 'CARRIAGE',      category: 'Transport',  hint: 'Horse-drawn vehicle' },
      { word: 'DRIFTWOOD',     category: 'Nature',     hint: 'Wood washed ashore' },
      { word: 'ELEPHANT',      category: 'Animal',     hint: 'Largest land animal' },
      { word: 'FORTRESS',      category: 'Structure',  hint: 'Heavily defended castle' },
      { word: 'GRAPEVINE',     category: 'Plant',      hint: 'Rumours travel on it' },
      { word: 'HOURGLASS',     category: 'Object',     hint: 'Measures time with sand' },
      { word: 'ICICLE',        category: 'Nature',     hint: 'Hanging frozen water' },
      { word: 'JELLYFISH',     category: 'Animal',     hint: 'Boneless ocean drifter' },
      { word: 'LABYRINTH',     category: 'Structure',  hint: 'Complex maze' },
      { word: 'MOONLIGHT',     category: 'Nature',     hint: "Night's soft glow" },
      { word: 'NIGHTMARE',     category: 'Dream',      hint: 'A frightening sleep vision' },
      { word: 'OBSIDIAN',      category: 'Mineral',    hint: 'Volcanic black glass' },
      { word: 'KALEIDOSCOPE',  category: 'Toy',        hint: 'Colorful rotating patterns' },
      { word: 'ABSINTHE',      category: 'Drink',      hint: 'Potent green herbal spirit' },
      { word: 'BRIMSTONE',     category: 'Mineral',    hint: 'Old name for sulfur; fire and ___' },
      { word: 'CAMOUFLAGE',    category: 'Concept',    hint: 'Blend into your surroundings' },
      { word: 'DINOSAUR',      category: 'Animal',     hint: 'Ruled Earth millions of years ago' },
      { word: 'EQUINOX',       category: 'Astronomy',  hint: 'Day and night are equal length' },
      { word: 'FILIGREE',      category: 'Art',        hint: 'Delicate twisted wire ornament' },
      { word: 'GLACIAL',       category: 'Nature',     hint: 'Relating to ice ages and glaciers' },
      { word: 'HALLMARK',      category: 'Concept',    hint: 'Distinguishing feature of quality' },
      { word: 'ILLUSION',      category: 'Concept',    hint: 'Something that deceives the eye' },
      { word: 'JETTISON',      category: 'Action',     hint: 'Throw overboard in an emergency' },
      { word: 'KINGFISHER',    category: 'Bird',       hint: 'Vivid blue bird that dives for fish' },
      { word: 'LUMINOUS',      category: 'Concept',    hint: 'Glowing with light' },
      { word: 'MAELSTROM',     category: 'Nature',     hint: 'Powerful whirlpool; chaos' },
      { word: 'NEBULOUS',      category: 'Concept',    hint: 'Vague and unclear, like a nebula' },
      { word: 'OVERTURE',      category: 'Music',      hint: 'Opening piece of an opera' },
      { word: 'PARCHMENT',     category: 'Material',   hint: 'Ancient writing surface from animal skin' },
      { word: 'QUICKSAND',     category: 'Nature',     hint: 'Loose wet sand that swallows things' },
      { word: 'RECKONING',     category: 'Concept',    hint: 'Day of ___ — time of judgment' },
      { word: 'SARCOPHAGUS',   category: 'History',    hint: 'Stone coffin of ancient Egypt' },
      { word: 'THUNDERCLAP',   category: 'Weather',    hint: 'Sudden loud crack of thunder' },
      { word: 'UNDERWORLD',    category: 'Mythology',  hint: 'Realm of the dead in Greek myth' },
      { word: 'VENOMOUS',      category: 'Animal',     hint: 'Delivers poison through a bite or sting' },
      { word: 'WHIRLPOOL',     category: 'Nature',     hint: 'Circular current of spinning water' },
      { word: 'XENOPHOBIA',    category: 'Concept',    hint: 'Fear or dislike of foreigners' },
      { word: 'ZEPPELIN',      category: 'Transport',  hint: 'Giant rigid airship' },
    ],
  },
};

export const LEVEL_ORDER = ['easy', 'medium', 'hard'];
